version: "3"

services:
  budibase:
    restart: unless-stopped
    image: budibase/budibase:latest
    ports:
      - "8080:80"
    environment:
      JWT_SECRET: <secret>
      MINIO_ACCESS_KEY: <secret>
      MINIO_SECRET_KEY: <secret>
      REDIS_PASSWORD: <secret>
      COUCHDB_USER: <secret>
      COUCHDB_PASSWORD: <secret>
      INTERNAL_API_KEY: <secret>
    volumes:
      - budibase_data:/data

  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: <secret>
      MYSQL_DATABASE: <secret>
      MYSQL_USER: <secret>
      MYSQL_PASSWORD: <secret>
      TZ: Asia/Tokyo
    ports:
      - "33061:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./sqldata:/sqldata
      - ~/docker-volume/mysql/<secret>:/var/lib/mysql

volumes:
  budibase_data:
    driver: local